version: "3"
services:
  app:
    depends_on:
     - db
    image: socialworky/geo-locations-dev:${GIT_SHA}
    restart: always
    container_name: geo-location-app
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_SSL: ${DB_SSL}
      TOKEN_NEWS_API: ${TOKEN_NEWS_API}
    dns:
      - 1.1.1.1
  db:
    container_name: postgresDB-geo
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres-db-geo:/var/lib/postgresql/data
  
  pgAdmin:
    depends_on:
      - db
    container_name: pgAdmin-geo
    image: dpage/pgadmin4:6.17
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    volumes:
      - pgadmin-data-geo:/var/lib/pgadmin

volumes:
  postgres-db-geo:
    external: false
  pgadmin-data-geo:
    external: false
